### ISSUE TITLE
when i run ng serve , i had the error()

### ISSUE THREAD

**Issue by sivaprabug** [fvilers/angular2-training#1]
when i run ng serve , i had the error()

![image](https://cloud.githubusercontent.com/assets/2444608/23461816/6e3fd142-feb1-11e6-8b4b-600d85a5ec61.png)

**Comment by fvilers** [comment]
Could you run `ng --version` and paste the output?

**Comment by sivaprabug** [comment]
FYI

![image](https://cloud.githubusercontent.com/assets/2444608/23461953/fb6bcaee-feb1-11e6-9d3b-6de82028250b.png)

**Comment by fvilers** [comment]
You seems to have an RC0 version installed. Could you update it to **1.0.0-beta.28.3** and try again? It is stated in the [README](https://github.com/fvilers/angular2-training/blob/master/README.md) that the application has been generated with a newer version of angular-cli.

**Comment by sivaprabug** [comment]
Hi,

How to install a particular version

**Comment by fvilers** [comment]
https://docs.npmjs.com/getting-started/updating-global-packages

**Comment by sivaprabug** [comment]
I uninstall the global angular-cli using below steps

npm uninstall -g @angular/cli
npm cache clean

how can i install  angular-cli 1.0.0-beta.28.3  Version ?

**Comment by fvilers** [comment]
`npm install angular-cli` (without '@')

**Comment by sivaprabug** [comment]
Yeah done

**_npm install -g angular-cli@1.0.0-beta.28.3_**

**Comment by fvilers** [comment]
Does it work now? Can I close the issue?

**Comment by sivaprabug** [comment]
@fvilers  please close the issues. Thanks lot

**Comment by fvilers** [comment]
Great news. Have fun with the demo!
