### ISSUE TITLE
No heroes are returned

### ISSUE THREAD

**Issue by worming004** [fvilers/angular2-training#8]
Hello Guys,

I was able to install all components and run them.
My remaining problem is I cannot see any heroes on http://localhost:4200/heroes page. each search returns an empty collections.
It is because the database is empty ? mongoose do not find the database ? Did I miss a step ? I didn't have any error to help me.

Thanks for your support and for your demo

**Comment by fvilers** [comment]
Hi @worming004 !

Thanks for your interest in this application. I've updated the README.md file to add some instructions, especially for the [development server](https://github.com/fvilers/angular2-training/blob/master/README.md#database-seeding) and [database seeding](https://github.com/fvilers/angular2-training/blob/master/README.md#database-seeding). Feel free to ask any further questions in case of need.

**Comment by worming004** [comment]
Hi,
Thanks for your help, it worked for me :)

**Comment by fvilers** [comment]
Great to read! May I ask you a question? How did you find our repository? Did you attend one of our Angular Training session?
